# Generated by Django 5.2.4 on 2025-07-13 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheel_spec', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wheelspecification',
            name='formNumber',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
